### ISSUE TITLE
Duplicate contract names found for OwnableDelegateProxy.

### ISSUE THREAD

**Issue by IPIvliev** [ProjectOpenSea/opensea-creatures#128]
> Duplicate contract names found for OwnableDelegateProxy.
> This can cause errors and unknown behavior. Please rename one of your contracts.

I get the error while deploing the contract as it was wroten: 
>>> yarn truffle deploy --network rinkeby

**Comment by soliditywiz** [comment]
Getting the same issue along with:

    Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
   --> /C/Users/Wiz/opensea-creatures-master/contracts/CreatureFactory.sol:137:9:
    |
137 |         address _from,
    |         ^^^^^^^^^^^^^

,Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
   --> /C/Users/Wiz/opensea-creatures-master/contracts/CreatureFactory.sol:172:22:
    |
172 |     function ownerOf(uint256 _tokenId) public view returns (address _owner) {

**Comment by soliditywiz** [comment]
Figured out a solution! 

I imported the ERC721Tradable.sol contract into ERC1155Tradable then got rid of the OwnableDelegateProxy & ProxyRegistry contracts in ERC1155Tradable. (Don't need them because they are being imported from ERC721Tradable.)

If you want, just paste the following from line 1 to line 19 and you should be good to go!

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "openzeppelin-solidity/contracts/access/Ownable.sol";
import "openzeppelin-solidity/contracts/token/ERC1155/ERC1155.sol";
import "openzeppelin-solidity/contracts/utils/math/SafeMath.sol";
import "openzeppelin-solidity/contracts/utils/Strings.sol";

import "./common/meta-transactions/ContentMixin.sol";
import "./common/meta-transactions/NativeMetaTransaction.sol";

import "./ERC721Tradable.sol"; // imported it here

//contract OwnableDelegateProxy { }

//contract ProxyRegistry {
//  mapping(address => OwnableDelegateProxy) public proxies;
//}

**Comment by sometimescasey** [comment]
Thanks @WizDevelop - wouldn't have guessed that! Can also import just those two definitions. Not sure why they didn't do this in the first place, seeing as the code for OwnableDelegateProxy and ProxyRegistry is identical between both files. 😕 

```
import { OwnableDelegateProxy, ProxyRegistry } from "./ERC721Tradable.sol";

// contract OwnableDelegateProxy { }

// contract ProxyRegistry {
//   mapping(address => OwnableDelegateProxy) public proxies;
// }
```

**Comment by damianlluch** [comment]
Hi, the WyvernProxyRegistry contract is the one in charge of registering a new proxy by the Owner in OpenSea? if I want to approve my own proxy, should I interact with this contract?

thanks
